/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/jv-searchengine/public/jv-search/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search job vacancies
         * @description Searches the EURES job vacancy database using a combination of keyword, location,
         *     occupation, skill, and filter criteria. Supports pagination and returns both matched
         *     vacancies and aggregated facet counts.
         *
         *     All filter arrays accept empty arrays to indicate no filter is applied. The
         *     `requestLanguage` field controls the language of returned text fields.
         */
        post: operations["searchJobVacancies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shared-data-rest-api/public/reference/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get supported languages
         * @description Returns the list of all languages supported by the EURES portal. Each entry contains
         *     the internal numeric ID, the ISO 639-1 language code, and the language name in its
         *     native script. Returns 26 languages total.
         */
        get: operations["getReferenceLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shared-data-rest-api/public/reference/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get supported countries
         * @description Returns the list of ISO 3166-1 alpha-2 country codes for all countries covered by
         *     EURES. Includes EU member states plus EFTA countries (Iceland, Liechtenstein,
         *     Norway, Switzerland). Returns 31 country codes total.
         */
        get: operations["getReferenceCountries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shared-data-rest-api/public/reference/nace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get NACE sector classifications
         * @description Returns the list of NACE (Nomenclature of Economic Activities) sector classification
         *     codes used by EURES. Returns 21 entries at level 1 (top-level divisions), using
         *     NACE Revision 2.0. The `code` field corresponds to the uppercase letter codes used
         *     in job search requests as lowercase values in `sectorCodes`.
         */
        get: operations["getReferenceNace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jv-searchengine/public/jv/id/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job vacancy detail
         * @description Retrieves the full detail of a single job vacancy by its base64-encoded identifier.
         *     Returns all language profiles, employer details, location data, application
         *     instructions, and translation metadata.
         */
        get: operations["getJobVacancyById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jv-searchengine/public/statistics/getNumberOfJobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get total job count
         * @description Returns the total number of active job vacancies in the EURES portal.
         */
        get: operations["getNumberOfJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jv-searchengine/public/statistics/getCountryStats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job statistics by country
         * @description Returns hierarchical statistics of job vacancies grouped by country and NUTS
         *     sub-regions. Each country entry contains nested region entries in `children`.
         */
        get: operations["getCountryStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jv-searchengine/public/statistics/getSectorStats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job statistics by NACE sector
         * @description Returns job vacancy counts grouped by NACE economic sector codes.
         */
        get: operations["getSectorStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jv-searchengine/public/statistics/getOccupationStats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job statistics by occupation
         * @description Returns top ESCO occupation categories ranked by vacancy count.
         */
        get: operations["getOccupationStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jv-searchengine/public/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get search engine configuration
         * @description Returns search engine configuration key-value pairs.
         */
        get: operations["getSearchEngineProperties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jv-searchengine/public/translation/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check if translation is enabled
         * @description Returns whether machine translation is enabled for the search engine.
         */
        get: operations["getTranslationEnabled"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jv-searchengine/public/translation/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get translation language codes
         * @description Returns the list of ISO 639-1 language codes supported for machine translation.
         */
        get: operations["getTranslationLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/autocomplete-repository-rest-api/public/v2.0/occupations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Autocomplete occupation names
         * @description Returns type-ahead occupation name suggestions based on a keyword prefix.
         *     Results are ranked by vacancy frequency (most common first).
         */
        get: operations["autocompleteOccupations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shared-data-rest-api/public/reference/isoLanguages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all ISO 639-1 languages
         * @description Returns the complete list of ISO 639-1 languages with an `euresSupported` flag
         *     indicating which languages are fully supported by the EURES portal (26 supported,
         *     130+ total).
         */
        get: operations["getIsoLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shared-data-rest-api/public/esco/supportedLanguages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get ESCO supported language codes
         * @description Returns ISO 639-1 codes of languages supported by the ESCO classification system.
         */
        get: operations["getEscoSupportedLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shared-data-rest-api/public/esco/label/{lang}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve ESCO URIs to labels
         * @description Accepts a list of ESCO URIs (occupations, skills, ISCO codes) and returns their
         *     human-readable labels in the specified language.
         */
        post: operations["getEscoLabels"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shared-data-rest-api/public/esco/occupation/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get ESCO occupation hierarchy
         * @description Returns the full hierarchical tree of ESCO/ISCO occupation classifications.
         *     Top-level nodes are ISCO major groups (C0-C9), with nested ISCO sub-groups
         *     and individual ESCO occupation URIs as leaf nodes.
         */
        get: operations["getEscoOccupationTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/security/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description Returns the profile of the currently authenticated user. All personal fields
         *     are null for unauthenticated (anonymous) requests.
         */
        get: operations["getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shared-data-rest-api/public/properties/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get portal configuration
         * @description Returns public portal configuration as key-value pairs.
         */
        get: operations["getPublicProperties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shared-data-rest-api/public/menu/{section}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get portal menu entries
         * @description Returns navigation menu entries for a portal section.
         */
        get: operations["getMenuEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JobSearchRequest: {
            /**
             * @description Number of job vacancies to return per page.
             * @example 10
             */
            resultsPerPage: number;
            /**
             * @description 1-based page index for pagination.
             * @example 1
             */
            page: number;
            sortSearch: components["schemas"]["SortOrder"];
            /**
             * @description List of keyword search terms. An empty array performs an unfiltered search
             *     across all vacancies.
             */
            keywords: components["schemas"]["KeywordEntry"][];
            /**
             * @description Restricts results to vacancies published within the specified period.
             *     `LAST_VISIT` requires an authenticated session. Pass `null` to disable
             *     the publication date filter.
             * @example null
             * @enum {string|null}
             */
            publicationPeriod?: "LAST_DAY" | "LAST_THREE_DAYS" | "LAST_WEEK" | "LAST_MONTH" | "LAST_VISIT" | null;
            /**
             * @description List of ESCO occupation URI strings to filter by. An empty array applies
             *     no occupation filter.
             * @example []
             */
            occupationUris: string[];
            /**
             * @description List of ESCO skill URI strings to filter by. An empty array applies no
             *     skill filter.
             * @example []
             */
            skillUris: string[];
            /**
             * @description Filter by required work experience level. An empty array applies no
             *     experience filter. Use `NS` for "not specified".
             * @example []
             */
            requiredExperienceCodes: components["schemas"]["ExperienceCode"][];
            /**
             * @description Filter by working time arrangement. An empty array applies no schedule
             *     filter. Use `NS` for "not specified".
             * @example []
             */
            positionScheduleCodes: components["schemas"]["PositionScheduleCode"][];
            /**
             * @description Filter by NACE economic sector. Values are lowercase single-letter NACE
             *     division codes (e.g. `a` for Agriculture). An empty array applies no
             *     sector filter. Use `NS` for "not specified".
             * @example []
             */
            sectorCodes: components["schemas"]["SectorCode"][];
            /**
             * @description Filter by required education or qualification level. An empty array applies
             *     no education filter. Use `NS` for "not specified".
             * @example []
             */
            educationAndQualificationLevelCodes: components["schemas"]["EducationLevelCode"][];
            /**
             * @description Filter by type of employment offering. An empty array applies no offering
             *     type filter. Use `NS` for "not specified".
             * @example []
             */
            positionOfferingCodes: components["schemas"]["PositionOfferingCode"][];
            /**
             * @description Filter by geographic location using NUTS (Nomenclature of Territorial Units
             *     for Statistics) region codes. Codes can be country-level (e.g. `de`),
             *     region-level (e.g. `de1`), or `NS` for "not specified". The suffix `-NS`
             *     on a country code (e.g. `at-NS`) selects vacancies in that country where
             *     the location is not specified.
             * @example []
             */
            locationCodes: string[];
            /**
             * @description Filter by EURES flag status. `WITH` returns only EURES-flagged vacancies.
             *     `WITHOUT` returns only non-EURES-flagged vacancies. An empty array applies
             *     no EURES flag filter.
             * @example []
             */
            euresFlagCodes: components["schemas"]["EuresFlagCode"][];
            /**
             * @description Filter by additional employer benefit codes. Values are numeric codes
             *     represented as strings. An empty array applies no benefits filter.
             * @example []
             */
            otherBenefitsCodes: string[];
            /**
             * @description Filter by required language proficiency. Each entry is a string in the
             *     format `<isoCode>(<cefrLevel>)`, e.g. `de(C2)` for German at C2 level,
             *     `en(B1)` for English at B1 level.
             * @example []
             */
            requiredLanguages: string[];
            /**
             * @description Minimum number of open positions required for a vacancy to be included in
             *     results. Pass `null` to apply no minimum.
             * @example null
             */
            minNumberPost?: number | null;
            /**
             * @description Client-generated session identifier string. Used by the EURES backend for
             *     session tracking. Does not require authentication for public endpoints.
             * @example session-abc123
             */
            sessionId: string;
            /**
             * @description ISO 639-1 language code expressing the user's preferred language for content
             *     retrieval. Pass `null` if no preference is set.
             * @example null
             */
            userPreferredLanguage?: string | null;
            /**
             * @description ISO 639-1 language code controlling the language of returned text content
             *     such as job titles and descriptions. Must match a language code supported
             *     by the /reference/languages endpoint.
             * @example en
             */
            requestLanguage: string;
        };
        KeywordEntry: {
            /**
             * @description The search term or phrase to match against job vacancies.
             * @example software engineer
             */
            keyword: string;
            /**
             * @description Controls which fields the keyword is matched against. Values correspond
             *     to the advanced search form fields on the EURES portal.
             * @example EVERYWHERE
             * @enum {string}
             */
            specificSearchCode: "EVERYWHERE" | "TITLE" | "DESCRIPTION" | "EMPLOYER" | "LEGAL_ID" | "JOB_VACANCY_ID";
        };
        JobSearchResponse: {
            /**
             * @description Total number of job vacancies matching the search criteria across all pages.
             * @example 1787657
             */
            numberRecords: number;
            /** @description Page of job vacancy objects matching the search criteria. */
            jvs: components["schemas"]["JobVacancy"][];
            facets: components["schemas"]["FacetMap"];
        };
        JobVacancy: {
            /**
             * @description Job vacancy title in the language determined by `requestLanguage`.
             * @example Software Engineer
             */
            title: string;
            /**
             * @description Full job description in the language determined by `requestLanguage`.
             *     Content is HTML-formatted and may contain tags such as `<p>`, `<ul>`, `<li>`.
             * @example <p>We are looking for a Software Engineer...</p>
             */
            description: string;
            /**
             * @description Opaque vacancy identifier. Observed values are base64-encoded strings.
             *     Use this value for deduplication and potential detail lookups.
             * @example MTAwMDEtMTAwMTEzOTMxMS1TIDE
             */
            id: string;
            /**
             * Format: int64
             * @description Unix timestamp in milliseconds (epoch ms) when the vacancy was created.
             * @example 1739403609768
             */
            creationDate: number;
            /**
             * Format: int64
             * @description Unix timestamp in milliseconds (epoch ms) of the last modification.
             * @example 1768605849756
             */
            lastModificationDate: number;
            /**
             * @description Number of open positions available for this vacancy.
             * @example 1
             */
            numberOfPosts: number;
            /**
             * @description Maps ISO 3166-1 alpha-2 uppercase country codes to arrays of NUTS region
             *     codes indicating where the vacancy is located. A vacancy may span multiple
             *     countries and regions.
             * @example {
             *       "DE": [
             *         "DE12B"
             *       ]
             *     }
             */
            locationMap: {
                [key: string]: string[];
            };
            /**
             * @description Indicates whether the vacancy is flagged as a EURES vacancy, meaning it is
             *     cross-border in nature and promoted through the EURES network.
             * @example false
             */
            euresFlag: boolean;
            /**
             * @description List of ESCO URIs classifying the occupation(s) associated with this vacancy.
             *     May include both occupation-level URIs and ISCO classification URIs.
             * @example [
             *       "http://data.europa.eu/esco/occupation/f2b15a0e-e65a-438a-affb-29b9d50b77d1",
             *       "http://data.europa.eu/esco/isco/C5243"
             *     ]
             */
            jobCategoriesCodes: string[];
            /**
             * @description Working time arrangements offered for this vacancy.
             * @example [
             *       "fulltime"
             *     ]
             */
            positionScheduleCodes: components["schemas"]["PositionScheduleCode"][];
            /**
             * @description Type of employment offering for this vacancy. Note: this field is singular
             *     (a single string value) unlike `positionScheduleCodes` which is an array.
             */
            positionOfferingCode: components["schemas"]["PositionOfferingCode"];
            employer: components["schemas"]["Employer"];
            /**
             * @description ISO 639-1 language codes for which translations are available in the
             *     `translations` map.
             * @example [
             *       "de"
             *     ]
             */
            availableLanguages: string[];
            /**
             * @description Relevance score for the vacancy relative to the search query. May be
             *     populated when `sortSearch` is set to `BEST_MATCH`, but has been observed
             *     as `null` in all captured responses.
             * @example null
             */
            score?: number | null;
            /**
             * @description Indicates how the vacancy content was translated or sourced. Observed
             *     value is `FIRST_LANGUAGE`, indicating content is in the vacancy's
             *     original language.
             * @example FIRST_LANGUAGE
             */
            translationType: string;
            /**
             * @description Map of ISO 639-1 language codes to translated vacancy content. Keys
             *     correspond to codes listed in `availableLanguages`.
             * @example {
             *       "de": {
             *         "title": "Software Engineer Safety (m/w/d)",
             *         "description": "<p>...</p>"
             *       }
             *     }
             */
            translations: {
                [key: string]: components["schemas"]["VacancyTranslation"];
            };
        };
        VacancyTranslation: {
            /**
             * @description Translated vacancy title.
             * @example Software Engineer Safety (m/w/d)
             */
            title: string;
            /**
             * @description Translated vacancy description in HTML format.
             * @example <p>Wir suchen einen Software Engineer...</p>
             */
            description: string;
        };
        Employer: {
            /**
             * @description Legal or trading name of the employer.
             * @example SUSS MicroTec Solutions GmbH & Co. KG
             */
            name: string;
            /**
             * @description Legal identifier of the employer (e.g. company registration number).
             *     Frequently null in observed responses.
             * @example null
             */
            legalID?: string | null;
            /**
             * @description Code representing the size of the employer organisation. Frequently null
             *     in observed responses.
             * @example null
             */
            organisationSizeCode?: string | null;
            /**
             * @description Code representing the ownership type of the organisation (e.g. public,
             *     private). Frequently null in observed responses.
             * @example null
             */
            organisationOwnershipTypeCode?: string | null;
            /**
             * @description Employer website URL or domain. May be a bare domain without protocol
             *     (e.g. "www.example.com") rather than a fully-qualified URL.
             * @example www.suss.com
             */
            website?: string | null;
            /**
             * @description NACE sector codes associated with the employer. Frequently an empty array
             *     in observed responses.
             * @example []
             */
            sectorCodes: string[];
            /**
             * @description Free-text description of the employer. Frequently null in observed responses.
             * @example null
             */
            description?: string | null;
        };
        /**
         * @description Aggregated facet counts grouped by filter category. Each key is a facet category
         *     name and maps to a facet result containing a list of entries with codes and counts.
         *     Facet categories observed in responses are listed as properties; additional
         *     categories may appear.
         */
        FacetMap: {
            /** @description Facet counts for language skill requirements. */
            LANGUAGE_SKILLS?: components["schemas"]["FacetResult"];
            /** @description Facet counts for required experience levels. */
            REQUIRED_EXPERIENCE?: components["schemas"]["FacetResult"];
            /**
             * @description Hierarchical facet counts for geographic location. Top-level entries are
             *     country codes; `childrenList` contains NUTS sub-region entries.
             */
            POSITION_LOCATION?: components["schemas"]["FacetResult"];
            /** @description Facet counts for NACE economic sector codes. */
            NACE_CODE?: components["schemas"]["FacetResult"];
            /**
             * @description Facet counts by connection point (data provider / job board source).
             *     Codes are numeric strings.
             */
            CONNECTION_POINT_ID?: components["schemas"]["FacetResult"];
            /** @description Facet counts for EURES flag status. */
            EURES_FLAG?: components["schemas"]["FacetResult"];
            /** @description Facet counts for working time arrangements. */
            POSITION_SCHEDULE?: components["schemas"]["FacetResult"];
            /** @description Facet counts for employment offering types. */
            POSITION_OFFERING?: components["schemas"]["FacetResult"];
            /**
             * @description Hierarchical facet counts for education and qualification levels. May include
             *     EQF (European Qualifications Framework) level sub-entries in `childrenList`.
             */
            EDUCATION_AND_QUALIFICATION_LEVEL?: components["schemas"]["FacetResult"];
            /** @description Facet counts for additional employer benefits. Codes are numeric strings. */
            EXTRA_BENEFIT?: components["schemas"]["FacetResult"];
        } & {
            [key: string]: components["schemas"]["FacetResult"];
        };
        FacetResult: {
            facetEntriesList: components["schemas"]["FacetEntry"][];
        };
        FacetEntry: {
            /**
             * @description The filter code value for this facet entry. Meaning depends on the parent
             *     facet category (e.g. a language code, a NUTS code, or a numeric string).
             * @example en
             */
            code: string;
            /**
             * @description Number of matching job vacancies for this facet value.
             * @example 68096
             */
            count: number;
            /**
             * @description Nested child facet entries for hierarchical facets (e.g. NUTS sub-regions
             *     under a country, or EQF levels under an education level). Empty array when
             *     the facet is not hierarchical or has no children.
             */
            childrenList: components["schemas"]["FacetEntry"][];
        };
        Language: {
            /**
             * @description Internal numeric language identifier used by the EURES system.
             * @example 6
             */
            id: number;
            /**
             * @description ISO 639-1 two-letter language code (lowercase).
             * @example en
             */
            isoCode: string;
            /**
             * @description Language name in its native script.
             * @example English
             */
            label: string;
        };
        NaceEntry: {
            /**
             * @description Internal numeric identifier for the NACE entry.
             * @example 1
             */
            id: number;
            /**
             * @description NACE division code in uppercase (e.g. `A` for Agriculture, Forestry and
             *     Fishing). When used as a filter value in `sectorCodes`, this code must be
             *     passed as lowercase (e.g. `a`).
             * @example A
             */
            code: string;
            /**
             * @description Hierarchy level of the NACE entry. All returned entries are at level 1.
             * @example 1
             */
            level: number;
            /**
             * @description NACE revision version string.
             * @example 2.0
             */
            revision: string;
        };
        IsoLanguage: {
            /**
             * @description Internal numeric language identifier.
             * @example 6
             */
            id: number;
            /**
             * @description ISO 639-1 two-letter language code (lowercase).
             * @example en
             */
            isoCode: string;
            /**
             * @description Language name in English.
             * @example English
             */
            label: string;
            /**
             * @description Whether this language is fully supported by the EURES portal.
             * @example true
             */
            euresSupported: boolean;
        };
        OccupationTreeNode: {
            /**
             * Format: uri
             * @description ESCO or ISCO classification URI. Top-level nodes use ISCO major group URIs
             *     (e.g. `http://data.europa.eu/esco/isco/C0`), leaf nodes use ESCO occupation URIs.
             * @example http://data.europa.eu/esco/isco/C2
             */
            uri: string;
            /** @description Child classification nodes. Empty array for leaf occupations. */
            childNodes: components["schemas"]["OccupationTreeNode"][];
        };
        /**
         * @description Full detail of a single job vacancy. Contains all language profiles, employer
         *     information, location data, application instructions, and translation metadata.
         */
        JobVacancyDetail: {
            /**
             * @description Base64-encoded vacancy identifier.
             * @example MTAwMDEtMTAwMTEzOTMxMS1TIDE
             */
            id: string;
            /**
             * @description Numeric reference string for the vacancy.
             * @example 100113931
             */
            reference: string;
            /**
             * @description Numeric document identifier string.
             * @example 10001
             */
            documentId: string;
            /**
             * @description Numeric identifier for the data source (connection point / job board).
             * @example 1001
             */
            connectionPointId: number;
            /**
             * @description Source system identifier string.
             * @example PES-SWEDEN
             */
            source: string;
            /**
             * Format: int64
             * @description Unix timestamp in milliseconds when the vacancy was created.
             * @example 1739403609768
             */
            creationDate: number;
            /**
             * Format: int64
             * @description Unix timestamp in milliseconds of the last modification, or null.
             */
            lastModificationDate?: number | null;
            /**
             * @description ISO 639-1 code of the vacancy's primary language.
             * @example sv
             */
            preferredLanguage: string;
            /** @description Map of ISO 639-1 language codes to the full vacancy profile in that language. */
            jvProfiles: {
                [key: string]: components["schemas"]["JobVacancyProfile"];
            };
            /**
             * @description Indicates the source of the vacancy language content.
             * @example FIRST_LANGUAGE
             */
            translationType: string;
            /** @description Machine translation metadata, or null when no translation is applied. */
            translation?: Record<string, never> | null;
        };
        /** @description A language-specific profile of a job vacancy. */
        JobVacancyProfile: {
            /**
             * @description ISO 639-1 code identifying the language of this profile.
             * @example sv
             */
            languageVersion?: string;
            /** @description Vacancy title in this language profile. */
            title?: string;
            /**
             * @description Number of open positions.
             * @example 1
             */
            numberOfPosts?: number;
            euresFlag?: boolean;
            jobCategoriesCodes?: string[];
            positionOfferingCode?: components["schemas"]["PositionOfferingCode"];
            positionScheduleCodes?: components["schemas"]["PositionScheduleCode"][];
            /** @description Full vacancy description in HTML format. */
            description?: string;
            locations?: components["schemas"]["Location"][];
            employer?: components["schemas"]["Employer"];
            /** @description Instructions for applying, may contain HTML. */
            applicationInstructions?: string[];
            /**
             * @description Application deadline as ISO 8601 date, or null.
             * @example 2025-06-30
             */
            lastApplicationDate?: string | null;
        };
        /** @description Geographic location associated with a job vacancy. */
        Location: {
            /**
             * @description ISO 3166-1 alpha-2 country code (lowercase).
             * @example se
             */
            countryCode?: string;
            /**
             * @description NUTS region code.
             * @example SE110
             */
            region?: string;
            /**
             * @description City or municipality name.
             * @example Stockholm
             */
            cityName?: string;
            /**
             * @description Postal code.
             * @example 11428
             */
            postalCode?: string;
            addressLines?: string[];
        };
        OccupationAutocompleteResponse: {
            /** @description Occupation suggestions ranked by vacancy frequency. */
            results?: components["schemas"]["OccupationSuggestion"][];
        };
        OccupationSuggestion: {
            /**
             * @description Number of active vacancies matching this suggestion.
             * @example 4821
             */
            frequency?: number;
            /**
             * @description ISO 639-1 code of the suggestion language.
             * @example de
             */
            language?: string;
            /**
             * @description Suggested occupation name.
             * @example Softwareentwickler/in
             */
            suggest?: string;
        };
        JobCountResponse: {
            /**
             * @description Total count of active job vacancies.
             * @example 2539302
             */
            numberOfJobs?: number;
        };
        /** @description Base structure for statistical breakdown entries. */
        StatEntry: {
            /** @description Human-readable name, or null. */
            label?: string | null;
            /** @description Classification code (context-dependent). */
            code?: string;
            /** @description Number of job vacancies. */
            jobs?: number;
            /** @description Number of positions, or null. */
            posts?: number | null;
            /**
             * Format: int64
             * @description Timestamp when this statistic was computed.
             */
            date?: number;
        };
        CountryStatEntry: components["schemas"]["StatEntry"] & {
            /** @description NUTS region sub-entries. */
            children?: components["schemas"]["RegionStatEntry"][];
        };
        RegionStatEntry: components["schemas"]["StatEntry"] & {
            children?: unknown[];
        };
        SectorStatEntry: components["schemas"]["StatEntry"] & {
            children?: unknown[];
        };
        OccupationStatEntry: components["schemas"]["StatEntry"] & {
            children?: unknown[];
        };
        /** @description Profile of the currently authenticated user. All fields null for anonymous users. */
        UserProfile: {
            userId?: string | null;
            euLoginId?: string | null;
            firstname?: string | null;
            lastname?: string | null;
            mainEmail?: string | null;
            preferredLanguage?: string | null;
            lastModificationDate?: string | null;
            status?: string | null;
            mainRole?: string | null;
            rights?: string[];
        };
        /** @description Navigation menu entry for a portal section. */
        MenuEntry: {
            /**
             * @description i18n key for the display label.
             * @example menu.jobseekers.find_a_job
             */
            labelKey?: string;
            /**
             * @description Relative or absolute URL.
             * @example /portal/jv-se/home
             */
            url?: string;
            /**
             * @description Application module identifier.
             * @example PORTAL_WEB
             */
            applicationName?: string;
            /**
             * @description Internal page code.
             * @example find_a_job
             */
            pageCode?: string;
        };
        /**
         * @description Sort order for returned job vacancies.
         *     - `BEST_MATCH`: Sort by relevance score relative to the search keywords.
         *     - `MOST_RECENT`: Sort by publication/creation date, newest first.
         * @example BEST_MATCH
         * @enum {string}
         */
        SortOrder: "BEST_MATCH" | "MOST_RECENT";
        /**
         * @description Required work experience level code. `NS` means "not specified".
         * @example between_2_and_5_years
         * @enum {string}
         */
        ExperienceCode: "none_required" | "up_to_1_year" | "between_1_and_2_years" | "between_2_and_5_years" | "more_than_5_years" | "NS";
        /**
         * @description Working time arrangement code. `NS` means "not specified".
         * @example fulltime
         * @enum {string}
         */
        PositionScheduleCode: "fulltime" | "parttime" | "flextime" | "NS";
        /**
         * @description NACE economic sector code (lowercase single letter corresponding to NACE divisions
         *     A through U). `NS` means "not specified".
         * @example q
         * @enum {string}
         */
        SectorCode: "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "NS";
        /**
         * @description Required education or qualification level code. `NS` means "not specified".
         *     Facet responses may include more granular EQF sub-codes (e.g. `eqf_8`) in
         *     `childrenList`, but these are not used as filter values in search requests.
         * @example bachelor
         * @enum {string}
         */
        EducationLevelCode: "basic" | "medium" | "bachelor" | "master" | "tertiary" | "doctoral" | "NS";
        /**
         * @description Type of employment offering. `NS` means "not specified".
         * @example directhire
         * @enum {string}
         */
        PositionOfferingCode: "apprenticeship" | "contract" | "contracttohire" | "directhire" | "internship" | "oncall" | "recruitmentreserve" | "seasonal" | "selfemployed" | "temporary" | "temporarytohire" | "volunteer" | "NS";
        /**
         * @description EURES flag filter value.
         *     - `WITH`: Vacancy is flagged as a EURES cross-border vacancy.
         *     - `WITHOUT`: Vacancy is not flagged as a EURES vacancy.
         * @example WITH
         * @enum {string}
         */
        EuresFlagCode: "WITH" | "WITHOUT";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchJobVacancies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobSearchRequest"];
            };
        };
        responses: {
            /** @description Successful job vacancy search response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSearchResponse"];
                };
            };
        };
    };
    getReferenceLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of supported languages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Language"][];
                };
            };
        };
    };
    getReferenceCountries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of country codes (ISO 3166-1 alpha-2) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    getReferenceNace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of NACE classification entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NaceEntry"][];
                };
            };
        };
    };
    getJobVacancyById: {
        parameters: {
            query?: {
                /**
                 * @description ISO 639-1 language code for the response content.
                 * @example de
                 */
                requestLang?: string;
                /**
                 * @description User's preferred language code, or null.
                 * @example null
                 */
                preferredLang?: string | null;
            };
            header?: never;
            path: {
                /**
                 * @description Base64-encoded vacancy identifier from search results.
                 * @example MTAwMDEtMTAwMTEzOTMxMS1TIDE
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full vacancy detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobVacancyDetail"];
                };
            };
        };
    };
    getNumberOfJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Total job count */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCountResponse"];
                };
            };
        };
    };
    getCountryStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Country-level job statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryStatEntry"][];
                };
            };
        };
    };
    getSectorStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sector-level job statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorStatEntry"][];
                };
            };
        };
    };
    getOccupationStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Occupation-level job statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OccupationStatEntry"][];
                };
            };
        };
    };
    getSearchEngineProperties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration properties */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getTranslationEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Translation enabled status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    getTranslationLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of translation language codes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    autocompleteOccupations: {
        parameters: {
            query: {
                /**
                 * @description ISO 639-1 language code for suggestions.
                 * @example de
                 */
                language: string;
                /**
                 * @description Search prefix for occupation names.
                 * @example Software
                 */
                keyword: string;
                /**
                 * @description Maximum number of suggestions to return.
                 * @example 10
                 */
                nbResults?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Occupation autocomplete suggestions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OccupationAutocompleteResponse"];
                };
            };
        };
    };
    getIsoLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full ISO language list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IsoLanguage"][];
                };
            };
        };
    };
    getEscoSupportedLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of ESCO-supported language codes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    getEscoLabels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description ISO 639-1 language code for returned labels.
                 * @example de
                 */
                lang: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example [
                 *       "http://data.europa.eu/esco/isco/C2511",
                 *       "http://data.europa.eu/esco/occupation/f2b15a0e-e65a-438a-affb-29b9d50b77d1"
                 *     ]
                 */
                "application/json": string[];
            };
        };
        responses: {
            /** @description Map of ESCO URIs to labels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getEscoOccupationTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hierarchical occupation tree */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OccupationTreeNode"][];
                };
            };
        };
    };
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    getPublicProperties: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portal configuration properties */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getMenuEntries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Portal section identifier.
                 * @example JOBSEEKERS
                 */
                section: "JOBSEEKERS" | "EMPLOYERS" | "LIVING" | "ABOUT" | "CONTACT_EURES_HELPDESK" | "MYEURES";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of menu entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuEntry"][];
                };
            };
        };
    };
}
