import {
  AGENT_CHAT_PROMPT_SECTIONS,
  AGENT_CHAT_SYSTEM_PROMPT,
  AGENT_TOOL_DESCRIPTIONS,
  buildPasteContextMessage,
} from "@/lib/agent/prompt";
import {
  RESUME_REVIEW_SYSTEM_PROMPT,
  RESUME_REVIEW_OUTPUT_FORMAT,
} from "@/lib/ai/prompts/resume-review";

const SCORES_LINE = "SCORES: overall=<0-100> impact=<0-100> clarity=<0-100> ats=<0-100>";

describe("agent chat system prompt", () => {
  it("is composed from named sections, all of which appear in the prompt", () => {
    const keys = Object.keys(AGENT_CHAT_PROMPT_SECTIONS);
    expect(keys).toEqual(
      expect.arrayContaining(["role", "capabilities", "limitations", "paste", "safety"]),
    );
    for (const key of keys) {
      expect(AGENT_CHAT_SYSTEM_PROMPT).toContain(
        AGENT_CHAT_PROMPT_SECTIONS[key as keyof typeof AGENT_CHAT_PROMPT_SECTIONS],
      );
    }
  });

  it("keeps what the agent can do separate from what it cannot read", () => {
    expect(AGENT_CHAT_PROMPT_SECTIONS.capabilities).toContain("add_job");
    expect(AGENT_CHAT_PROMPT_SECTIONS.limitations).toMatch(/cannot read/i);
    expect(AGENT_CHAT_PROMPT_SECTIONS.capabilities).not.toMatch(/cannot read/i);
  });

  // Measured, not assumed: without this, qwen3.5:9b extracted correctly and
  // then asked for confirmation in prose on 5 of 7 eval rows instead of
  // calling the tool, re-implementing the approval card in chat text.
  it("tells the model to call the tool instead of confirming in chat", () => {
    expect(AGENT_CHAT_PROMPT_SECTIONS.capabilities).toMatch(/never ask.*confirm in the chat/i);
    expect(AGENT_CHAT_PROMPT_SECTIONS.capabilities).toMatch(/never ask the user for optional fields/i);
  });

  it("tells the model not to echo a pasted description back", () => {
    expect(AGENT_CHAT_PROMPT_SECTIONS.paste).toMatch(/do not.*(repeat|echo|copy)/i);
  });

  it("names the approval verbs the UI actually uses", () => {
    expect(AGENT_CHAT_SYSTEM_PROMPT).toContain("Confirm");
    expect(AGENT_CHAT_SYSTEM_PROMPT).toContain("Cancel");
  });

  it("treats delimited pasted content as data, never as instructions", () => {
    expect(AGENT_CHAT_PROMPT_SECTIONS.safety).toMatch(/never.*instructions/i);
    expect(buildPasteContextMessage("<<<X>>>body<<<END X>>>")).toContain("<<<X>>>body<<<END X>>>");
    expect(buildPasteContextMessage("BLOCK")).toMatch(/data/i);
  });

  it("describes add_job without mentioning tools the chat does not expose", () => {
    expect(AGENT_TOOL_DESCRIPTIONS.add_job).toBeTruthy();
    expect(AGENT_TOOL_DESCRIPTIONS.add_job).not.toMatch(/upsert|allowDuplicate|update_job/);
  });

  // The review is generated by review_resume's own nested call now, so the
  // output format has no business in the chat prompt. Deleting it is the
  // point of the change, not a side effect: it was the longest block in the
  // prompt and the measured cause of qwen3.5:9b's add_job regression.
  it("no longer carries the review output format", () => {
    expect(AGENT_CHAT_SYSTEM_PROMPT).not.toContain(RESUME_REVIEW_OUTPUT_FORMAT);
    expect(AGENT_CHAT_SYSTEM_PROMPT).not.toContain("SCORES:");
    expect(RESUME_REVIEW_SYSTEM_PROMPT).toContain(RESUME_REVIEW_OUTPUT_FORMAT);
  });

  it("keeps the exact SCORES line the shared parser matches", () => {
    expect(RESUME_REVIEW_OUTPUT_FORMAT).toContain(SCORES_LINE);
    expect(RESUME_REVIEW_OUTPUT_FORMAT).toContain("## Grammar & Spelling");
  });

  it("no longer claims resumes are unreadable", () => {
    expect(AGENT_CHAT_SYSTEM_PROMPT).toContain("get_resume");
    expect(AGENT_CHAT_SYSTEM_PROMPT).not.toContain(
      "saved jobs, resumes, tasks",
    );
  });

  it("routes review requests to the tool instead of describing a review", () => {
    expect(AGENT_CHAT_PROMPT_SECTIONS).not.toHaveProperty("review");
    expect(AGENT_CHAT_PROMPT_SECTIONS.capabilities).toContain("review_resume");
    expect(AGENT_CHAT_PROMPT_SECTIONS.capabilities).toMatch(/never write a review yourself/i);
  });

  it("describes all three tools", () => {
    expect(Object.keys(AGENT_TOOL_DESCRIPTIONS)).toEqual([
      "add_job",
      "get_resume",
      "review_resume",
    ]);
  });

  // get_resume stays the on-ramp for reading a resume, but it is no longer
  // the review path — leaving the clause in gives the model two ways to
  // answer "review my resume" and it picks the wrong one.
  it("strips the review clause from the get_resume description", () => {
    expect(AGENT_TOOL_DESCRIPTIONS.get_resume).not.toMatch(/review/i);
    expect(AGENT_TOOL_DESCRIPTIONS.review_resume).toMatch(/review/i);
  });
});
